import Head from "next/head";
import styles from "../styles/Home.module.css";

class Node {
  constructor(row, col) {
    this.row = row;
    this.col = col;
    this.isVisited = false;
    this.isStart = false;
    this.isEnd = false;
  }
}
export default function Home() {
  let grid = [];
  useMemo(() => {
    for (let i = 0; i < 50; i++) {
      row = [];
      for (let j = 0; j < 50; j++) {
        const node = new Node(i, j);
        row.append(node);
      }
      grid.append(row);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {grid.map((row) => (
        <div key></div>
      ))}
    </div>
  );
}
