import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useMemo } from "react";
import Node from "../components/Node";

export default function Home() {
  let grid = [];
  for (let i = 0; i < 20; i++) {
    let row = [];
    for (let j = 0; j < 50; j++) {
      const node = { row: i, col: j };
      row.push(node);
    }
    grid.push(row);
  }

  return (
    <div className={styles.main}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {grid.map((row, index) =>
          row.map((node, index) => <Node key={index}></Node>)
        )}
      </div>
    </div>
  );
}
